### ISSUE TITLE
Server Error Error: Invalid hook call.

### ISSUE THREAD

**Issue by mcmwebsol** [JEverhart383/first-headless-project-decode-2023#1]
I get the below error on localhost:3000

Server Error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
resolveDispatcher
file:///C:/Users/path/Downloads/first-headless-project-decode-2023-main/node_modules/react/cjs/react.development.js (1476:13)
Object.useContext
file:///C:/Users/path/Downloads/first-headless-project-decode-2023-main/node_modules/react/cjs/react.development.js (1484:20)
Html
node_modules\next\dist\pages\_document.js (652:105)
processChild
file:///C:/Users/path/Downloads/first-headless-project-decode-2023-main/node_modules/react-dom/cjs/react-dom-server.node.development.js (3353:14)
resolve
file:///C:/Users/path/Downloads/first-headless-project-decode-2023-main/node_modules/react-dom/cjs/react-dom-server.node.development.js (3270:5)
ReactDOMServerRenderer.render

I tried running 
npm ls react 
and it shows
@faustwp/getting-started-example@0.1.0 c:\Users\path\Downloads\first-headless-project-decode-2023-main
+-- @wordpress/block-library@7.19.0
| +-- @wordpress/element@4.20.0
| | `-- react@17.0.2  deduped
| +-- @wordpress/icons@9.18.0
| | `-- @wordpress/element@5.4.0
| |   `-- react@18.2.0
| +-- @wordpress/notices@3.27.0
| | `-- @wordpress/data@8.4.0
| |   `-- @wordpress/element@5.4.0
| |     `-- react@18.2.0
| `-- @wordpress/primitives@3.25.0
|   `-- @wordpress/element@5.4.0
|     `-- react@18.2.0
`-- react@17.0.2

Is there a way to resolve this?
I'm running on Windows 10.

**Comment by jayanth-kumar-morem** [comment]
@mcmwebsol 
It appears that you have two different versions of React in your project. You have React v17.0.2 and React v18.2.0 installed. This can cause the "Invalid hook call" error you're encountering.

**Comment by mcmwebsol** [comment]
Okay, but how to do I fix that?  I haven't added anything to this project.

**Comment by JEverhart383** [comment]
@mcmwebsol what version of node/npm are you using? Might be worth trying to update

**Comment by mcmwebsol** [comment]
I was using npm 6.14.6 and node 12.18.4
I upgraded to npm 9.5.0 and node 18.15.0

Now I get a different error though:

warn  - ./node_modules/next/dist/pages/_error.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* c:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use!C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\next\dist\pages\_error.js
* c:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use!c:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\next\dist\pages\_error.js
error - ApolloError: Response not successful: Received status code 405
    at new ApolloError (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\errors\errors.cjs:34:28)
    at C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\core\core.cjs:1853:19
    at both (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\utilities\utilities.cjs:1068:53)
    at C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\utilities\utilities.cjs:1061:72
    at new Promise (<anonymous>)
    at Object.then (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\utilities\utilities.cjs:1061:24)
    at Object.error (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\utilities\utilities.cjs:1069:49)
    at notifySubscription (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\zen-observable\lib\Observable.js:140:18)
    at onNotify (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.error (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\zen-observable\lib\Observable.js:240:7) {
  graphQLErrors: [],
  clientErrors: [],
  networkError: Error [ServerError]: Response not successful: Received status code 405
      at Object.throwServerError (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\link\utils\utils.cjs:45:17)
      at parseJsonBody (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\link\http\http.cjs:275:15)
      at C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\link\http\http.cjs:311:48
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    },
    statusCode: 405,
    result: '<!DOCTYPE html><html><head><style data-next-hide-fouc="true">body{display:none}</style><noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>405: Method Not Allowed</title><meta name="next-head-count" content="3"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1681228797120"></script><script src="/_next/static/chunks/webpack.js?ts=1681228797120" defer=""></script><script src="/_next/static/chunks/main.js?ts=1681228797120" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1681228797120" defer=""></script><script src="/_next/static/chunks/pages/_error.js?ts=1681228797120" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1681228797120" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1681228797120" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><div id="__next" data-reactroot=""><div style="font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div><style>\n' +
      '                body { margin: 0; color: #000; background: #fff; }\n' +
      '                .next-error-h1 {\n' +
      '                  border-right: 1px solid rgba(0, 0, 0, .3);\n' +
      '                }\n' +
      '\n' +
      '                @media (prefers-color-scheme: dark) {\n' +
      '                  body { color: #fff; background: #000; }\n' +
      '                  .next-error-h1 {\n' +
      '                    border-right: 1px solid rgba(255, 255, 255, .3);\n' +
      '                  }\n' +
      '                }</style><h1 class="next-error-h1" style="display:inline-block;margin:0;margin-right:20px;padding:0 23px 0 0;font-size:24px;font-weight:500;vertical-align:top;line-height:49px">405</h1><div style="display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle"><h2 style="font-size:14px;font-weight:normal;line-height:49px;margin:0;padding:0">Method Not Allowed.</h2></div></div></div></div><script src="/_next/static/chunks/react-refresh.js?ts=1681228797120"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":405}},"page":"/_error","query":{},"buildId":"development","isFallback":false,"gip":true,"locales":["en"],"scriptLoader":[]}</script></body></html>'
  },
  extraInfo: undefined,
  page: '/'
}
error - ApolloError: Response not successful: Received status code 405
    at new ApolloError (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\errors\errors.cjs:34:28)
    at C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\core\core.cjs:1853:19
    at both (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\utilities\utilities.cjs:1068:53)
    at C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\utilities\utilities.cjs:1061:72
    at new Promise (<anonymous>)
    at Object.then (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\utilities\utilities.cjs:1061:24)
    at Object.error (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\utilities\utilities.cjs:1069:49)
    at notifySubscription (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\zen-observable\lib\Observable.js:140:18)
    at onNotify (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.error (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\zen-observable\lib\Observable.js:240:7) {
  graphQLErrors: [],
  clientErrors: [],
  networkError: Error [ServerError]: Response not successful: Received status code 405
      at Object.throwServerError (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\link\utils\utils.cjs:45:17)
      at parseJsonBody (C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\link\http\http.cjs:275:15)
      at C:\Users\xyz\Downloads\first-headless-project-decode-2023-main\node_modules\@apollo\client\link\http\http.cjs:311:48
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    },
    statusCode: 405,
    result: '<!DOCTYPE html><html><head><style data-next-hide-fouc="true">body{display:none}</style><noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>405: Method Not Allowed</title><meta name="next-head-count" content="3"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1681228798344"></script><script src="/_next/static/chunks/webpack.js?ts=1681228798344" defer=""></script><script src="/_next/static/chunks/main.js?ts=1681228798344" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1681228798344" defer=""></script><script src="/_next/static/chunks/pages/_error.js?ts=1681228798344" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1681228798344" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1681228798344" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><div id="__next" data-reactroot=""><div style="font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div><style>\n' +
      '                body { margin: 0; color: #000; background: #fff; }\n' +
      '                .next-error-h1 {\n' +
      '                  border-right: 1px solid rgba(0, 0, 0, .3);\n' +
      '                }\n' +
      '\n' +
      '                @media (prefers-color-scheme: dark) {\n' +
      '                  body { color: #fff; background: #000; }\n' +
      '                  .next-error-h1 {\n' +
      '                    border-right: 1px solid rgba(255, 255, 255, .3);\n' +
      '                  }\n' +
      '                }</style><h1 class="next-error-h1" style="display:inline-block;margin:0;margin-right:20px;padding:0 23px 0 0;font-size:24px;font-weight:500;vertical-align:top;line-height:49px">405</h1><div style="display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle"><h2 style="font-size:14px;font-weight:normal;line-height:49px;margin:0;padding:0">Method Not Allowed.</h2></div></div></div></div><script src="/_next/static/chunks/react-refresh.js?ts=1681228798344"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":405}},"page":"/_error","query":{},"buildId":"development","isFallback":false,"gip":true,"locales":["en"],"scriptLoader":[]}</script></body></html>'
  },
  extraInfo: undefined,
  page: '/[...wordpressNode]'
}

Thanks

**Comment by JEverhart383** [comment]
@mcmwebsol I was able to find a few similar error reports in the Next.js repo:
https://github.com/vercel/next.js/issues/10739
https://github.com/vercel/next.js/discussions/32034

I'm not sure if that will help, but it seems like there are some issues with drive letter casing in the second discussion. I know we've had people use Faust successfully on Windows, so if you can share any details on what command prompt you're using, maybe we can shape this into some suggestions for Windows users.
